[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["devjobe <71590722+devjobe@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1"
itertools = "0.9"
